services:
  cms:
    image: ghcr.io/prabesh01/statamic:latest
    container_name: statamic_app
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./storage:/var/www/html/storage
      - ./content:/var/www/html/content
      - ./.env:/var/www/html/.env
      - ./users:/var/www/html/users
      - ./public/assets:/var/www/html/public/assets
